### ISSUE TITLE
ESXi installations fail at network customization

### ISSUE THREAD

**Issue by dmiyoshi1** [HewlettPackard/chef-provisioning-oneview#32]
ESXi SA agents are not available.  Therefore, after the ESXi host boots there are no agents available to run the network customizations.  I did get ESXi deployments to work but had to comment out the icsp_configure_networking method in customize_machine.rb file to avoid any network customization.  Could an "OS" var be added so that an if condition is set before than method?  Also, can another icsp_configure_networking method be created for ESXi deploys such that only the names are updated in ICSP?  Thanks. Dennis

**Comment by jsmartt** [comment]
Fixed with #33
