### ISSUE TITLE
Incorrect error message sent when executing provisioning command

### ISSUE THREAD

**Issue by jwenglishga** [HewlettPackard/chef-provisioning-oneview#37]
when I execute:
chef exec bundle exec chef-client -z cookbooks/provisioning_cookbook/recipes/default.rb

I get an error message back saying that it can't login to oneview. The actual error is that it can't login to icsp. Is there a way to get the message to be a little more helpful. 

[chef-stacktrace.out.txt](https://github.com/HewlettPackard/chef-provisioning-oneview/files/119719/chef-stacktrace.out.txt)

**Comment by jsmartt** [comment]
@jwenglishga , thanks for finding this! It even displays the wrong URL

Just created a PR for this. Once it's merged, you can pull the latest code and it'll be fixed. However, it won't make it into the official gem until the next release.

**Comment by jsmartt** [comment]
@jwenglishga & @ChrisLynchHP , this is now released on RubyGems, so if you upgrade it to 1.1.3, the error message should be fixed.

**Comment by jwenglishga** [comment]
Thanks!
